<a href="https://colab.research.google.com/github/ambruhsia/Zoomcamp-2026/blob/main/Homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Q1. Pandas version

In [3]:
# Q1. Pandas version
print(pd.__version__)

2.2.3


### Getting the data

In [4]:
# Download the dataset
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv -O car_fuel_efficiency_2026.csv

# Read the dataset with Pandas
df = pd.read_csv('car_fuel_efficiency_2026.csv')
display(df.head())

--2026-09-29 10:32:17--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.007s  

2026-09-29 10:32:17 (81.9 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]



,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


### Q2. Records count

In [5]:
# Q2. Records count
num_records = len(df)
print(f"Number of records in the dataset: {num_records}")

Number of records in the dataset: 10000


### Q3. Fuel types

In [6]:
# Q3. Fuel types
num_fuel_types = df['fuel_type'].nunique()
print(f"Number of unique fuel types: {num_fuel_types}")

Number of unique fuel types: 3


### Q4. Missing values

In [7]:
# Q4. Missing values
missing_values_count = df.isnull().sum()
columns_with_missing_values = missing_values_count[missing_values_count > 0].index.tolist()
num_columns_with_missing_values = len(columns_with_missing_values)
print(f"Number of columns with missing values: {num_columns_with_missing_values}")
print(f"Columns with missing values: {columns_with_missing_values}")

Number of columns with missing values: 2
Columns with missing values: ['horsepower', 'acceleration']


### Q5. Max fuel efficiency

In [11]:
# Q5. Max fuel efficiency of cars from Asia
asia_cars = df[df['origin'] == 'Asia']
max_fuel_efficiency_asia = asia_cars['fuel_efficiency_mpg'].max()
print(f"Maximum fuel efficiency of cars from Asia: {max_fuel_efficiency_asia}")

Maximum fuel efficiency of cars from Asia: 41.2


### Q6. Median value of horsepower

In [9]:
# Q6. Median value of horsepower

# Initial median horsepower
median_horsepower_initial = df['horsepower'].median()
print(f"Initial median horsepower: {median_horsepower_initial}")

# Most frequent value of horsepower
most_frequent_horsepower = df['horsepower'].mode()[0]
print(f"Most frequent horsepower: {most_frequent_horsepower}")

# Fill missing values in 'horsepower' with the most frequent value
df_filled = df.copy()
df_filled['horsepower'].fillna(most_frequent_horsepower, inplace=True)

# New median horsepower after filling missing values
median_horsepower_after_fill = df_filled['horsepower'].median()
print(f"Median horsepower after filling missing values: {median_horsepower_after_fill}")

# Has it changed?
if median_horsepower_after_fill > median_horsepower_initial:
    print("Median has increased.")
elif median_horsepower_after_fill < median_horsepower_initial:
    print("Median has decreased.")
else:
    print("Median has not changed.")

Initial median horsepower: 254.0
Most frequent horsepower: 252.0
Median horsepower after filling missing values: 252.0
Median has decreased.


/tmp/ipykernel_560/3301013790.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filled['horsepower'].fillna(most_frequent_horsepower, inplace=True)


### Q7. Sum of weights (Linear Regression Implementation)

In [10]:
# Q7. Sum of weights

# Select all cars from Asia
asia_cars_q7 = df[df['origin'] == 'Asia']

# Select only columns vehicle_weight and model_year
asia_cars_q7_selected = asia_cars_q7[['vehicle_weight', 'model_year']]

# Select the first 7 values
asia_cars_q7_first_7 = asia_cars_q7_selected.head(7)

# Get the underlying NumPy array. Let's call it X.
X = asia_cars_q7_first_7.values
print("X array:\n", X)

# Compute matrix-matrix multiplication between the transpose of X and X. Let's call the result XTX.
XTX = X.T @ X
print("XTX matrix:\n", XTX)

# Invert XTX.
XTX_inv = np.linalg.inv(XTX)
print("Inverse of XTX:\n", XTX_inv)

# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print("y array:\n", y)

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv @ X.T @ y
print("w array (coefficients):\n", w)

# What's the sum of all the elements of the result?
sum_of_w = w.sum()
print(f"Sum of all elements of w: {sum_of_w:.4f}")

X array:
 [[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
XTX matrix:
 [[131950500  60750580]
 [ 60750580  28041424]]
Inverse of XTX:
 [[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
y array:
 [1100 1300  800  900 1000 1100 1200]
w array (coefficients):
 [0.13644777 0.2327492 ]
Sum of all elements of w: 0.3692
